language: 
  - objective-c
osx_image: 
  - xcode10.1
before_install:
   - pod cache clean --all    
   - pod update
install:
- gem install xcpretty-travis-formatter
script:
  - xcodebuild test -project 'BlockObserver.xcodeproj' -scheme 'BlockObserverTests' | xcpretty -f `xcpretty-travis-formatter`